### ISSUE TITLE
Potential bug in TemplateMatching.java (version 0.14)

### ISSUE THREAD

**Issue by bbli08** [lessthanoptimal/BoofCV#103]
In the following code snipet from boofcv.alg.feature.detect.template.TemplateMatching.java (at about line 112), N can be candidates.size, 

	public void process() {
		...
		int N = Math.min(maxMatches, candidates.size);

		QuickSelect.selectIndex(scores, N, candidates.size, indexes);

See exception when candidates.size is large, say 999.
ExpectedMatches is large which can trigger a potential bug in the BoofCV (ArrayIndexOutofBoundException): 999
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 712
	at org.ddogleg.sorting.QuickSelect.selectIndex(QuickSelect.java:301)
	at boofcv.alg.feature.detect.template.TemplateMatching.process(TemplateMatching.java:154)
...

According to the QuickSelect.selectIndex java doc at http://ddogleg.org/javadoc/index.html?org/ddogleg/sorting/CountingSort.html, N should be the k-th element instead, so it can be at most candidates.size -1.

Suggested fix:
int N = Math.min(maxMatches, candidates.size - 1);

**Comment by reconman** [comment]
Found the same issue just now, will this ever get fixed?

Can be reproduced with ExampleTemplateMatching by setting the `expectedMatches` parameter to 1000 for one of the images.

**Comment by lessthanoptimal** [comment]
@reconman Just tried that and nothing went wrong.

`drawRectangles(g2, image, templateCursor, maskCursor, 1000);`

Could you upload the modified example so I can replicate it? Thanks!

**Comment by lessthanoptimal** [comment]
If you're not using BoofCV 0.41 the switch to that.

**Comment by reconman** [comment]
I forgot, I also added a minimum distance to trigger the bug.

Here's my code: https://pastebin.com/n6huNveT
