### ISSUE TITLE
Fatal exception on 0.36-SNAPSHOT

### ISSUE THREAD

**Issue by rojepp** [lessthanoptimal/BoofCV#156]
I've been using 0.36-SNAPSHOT. In hindsight maybe that wasn't such a good idea. 
Recently this started happening when I open the QR reader in my app. I've even tried the same git commit that is in the play store, where the QR reader works, which leads me to believe something broke recently in snapshot. Are there different versions of 0.36 snapshots such that I could roll back to an earlier version? 

> FATAL EXCEPTION: main
    Process: heynow.ai.brilliant, PID: 3141
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/ddogleg/struct/FastQueue$Factory;
        at boofcv.alg.filter.binary.LinearExternalContours.<init>(LinearExternalContours.java:66)
        at boofcv.abst.filter.binary.BinaryContourFinderLinearExternal.<init>(BinaryContourFinderLinearExternal.java:49)
        at boofcv.factory.filter.binary.FactoryBinaryContourFinder.linearExternal(FactoryBinaryContourFinder.java:49)
        at boofcv.factory.shape.FactoryShapeDetector.polygonContour(FactoryShapeDetector.java:115)
        at boofcv.factory.shape.FactoryShapeDetector.polygon(FactoryShapeDetector.java:100)
        at boofcv.factory.fiducial.FactoryFiducial.qrcode(FactoryFiducial.java:199)
        at heynow.ai.brilliant.ui.screen_lane.LaneCameraActivity.<init>(LaneCameraActivity.kt:59)

This is in my build.gradle (android app)

```
    implementation ('org.boofcv:boofcv-android:0.36-SNAPSHOT') {
        // exclude group: 'com.google.protobuf'
    }
    implementation('org.boofcv:boofcv-core:0.36-SNAPSHOT') {
        exclude group: 'com.google.protobuf'
        exclude group: 'org.rauschig'
    }
```

**Comment by lessthanoptimal** [comment]
Try pulling git again or flushing your gradle/maven cache and downloading the latest SNAPSHOT. I think that should fix it. You need to use SNAPSHOT of GeoRegression and DDogleg now. To be safe I just updated latest jars to both of their maven repos.

**Comment by rojepp** [comment]
Actually I've reverted to 0.35 now, to make sure this does not happen again. I shouldn't have been on a snapshot to begin with :). Any timeframe for a stable 0.36 release? Thanks for all your work!

**Comment by lessthanoptimal** [comment]
1 to 4 months is my best guess now. You're welcome!
