### ISSUE TITLE
ConvertBufferedImage class doesn't initialize ImageBase.imageType

### ISSUE THREAD

**Issue by pcmoen** [lessthanoptimal/BoofCV#41]
The `ConvertBufferedImage` class uses the default constructors of the various ImageBase implementors. It then sets the various fields directly before returning its results.

Unfortunately the `imageType` field is not initialized by any of the methods.

This means that the returned images cannot be used by for example the new `FDistort` class.

The following is an example of a operation that cannot be applied to the returned images:
```java
		new FDistort(found, output).interpNN().scale().apply();
```

**Comment by lessthanoptimal** [comment]
Can you provide a more complete code example with any example data?  I'm not sure while image type is causing the issue.  Thanks.

**Comment by pcmoen** [comment]
I copied and modified one of the tests in TestConvertBufferedImage.java:

```java

	@Test
	public void extractInterleavedU8Foo() {
		BufferedImage origImg = TestConvertRaster.createByteBuff(imgWidth, imgHeight, 3, rand);

		InterleavedU8 found = ConvertBufferedImage.extractInterleavedU8(origImg);

		assertEquals(0, found.startIndex);
		assertEquals(imgWidth*3, found.stride);
		assertEquals(imgWidth, found.width);
		assertEquals(imgHeight, found.height);
		assertEquals(3, found.numBands);
		assertTrue(found.data != null);
		assertEquals(imgWidth * imgHeight * 3, found.data.length);

//		found.imageType = new ImageType<InterleavedU8>(ImageType.Family.INTERLEAVED, ImageDataType.U8, 3);

		InterleavedU8 output = new InterleavedU8(imgWidth/ 2, imgHeight / 2, 3);

		new FDistort(found, output).interpNN().scale().apply();

		// test a sub-image input
		origImg = origImg.getSubimage(1,2,5,6);

		found = ConvertBufferedImage.extractInterleavedU8(origImg);

		assertEquals(2 * 10 * 3 + 3, found.startIndex);
		assertEquals(imgWidth*3, found.stride);
		assertEquals(5, found.width);
		assertEquals(6, found.height);
		assertEquals(3, found.numBands);
	}
```

This will throw the following `NullPointException`

```
java.lang.NullPointerException
	at boofcv.factory.interpolate.FactoryInterpolation.createPixel(FactoryInterpolation.java:57)
	at boofcv.abst.distort.FDistort.interp(FDistort.java:216)
	at boofcv.abst.distort.FDistort.init(FDistort.java:101)
	at boofcv.abst.distort.FDistort.<init>(FDistort.java:79)
	at boofcv.io.image.TestConvertBufferedImage.extractInterleavedU8Foo(TestConvertBufferedImage.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

If you uncomment the `found.imageType` initialization the FDistort call succeeds.

**Comment by pcmoen** [comment]
This is using the latest source code from GitHub.

**Comment by lessthanoptimal** [comment]
Fixed bug.  Actually two bugs.  New argument constructor in Interleaved and SingleBand images was not correctly initializing image type and ConvertBufferedImage was not correctly setting the number of bands.

Thanks!

e62ef7e20fe314dabe1548276a90839070af8f85
