### ISSUE TITLE
A NullPointerException is thrown when the ImplOrientationImageAverageIntegral constructor is invoked

### ISSUE THREAD

**Issue by pcmoen** [lessthanoptimal/BoofCV#43]
The following NullPointerException is thrown when the ImplOrientationImageAverageIntegral constructor is invoked:

```
java.lang.NullPointerException
	at boofcv.alg.feature.orientation.impl.ImplOrientationImageAverageIntegral.setObjectRadius(ImplOrientationImageAverageIntegral.java:91)
	at boofcv.alg.feature.orientation.OrientationIntegralBase.<init>(OrientationIntegralBase.java:87)
	at boofcv.alg.feature.orientation.impl.ImplOrientationImageAverageIntegral.<init>(ImplOrientationImageAverageIntegral.java:56)
	at boofcv.alg.feature.orientation.impl.ImplOrientationImageAverageIntegralTest.testConstructor(ImplOrientationImageAverageIntegralTest.java:10)
[...]
```

This is caused by the base class `OrientationIntegralBase` calling the `setObjectRadius(double radius)` template method before the `ImplOrientationImageAverageIntegral.sampler` field have been initialized. 

The following unit test will trigger the exception.
```
package boofcv.alg.feature.orientation.impl;

import boofcv.struct.image.ImageFloat32;
import boofcv.struct.sparse.GradientValue_F32;
import org.junit.Test;

public class ImplOrientationImageAverageIntegralTest {
	@Test
	public void testConstructor() {
		new ImplOrientationImageAverageIntegral<ImageFloat32, GradientValue_F32>(0.5, 6, 1, 4, 0, ImageFloat32.class);
	}
}
```

**Comment by lessthanoptimal** [comment]
Thanks!  fixed in 335fa9474fa7d3e437571328324fa1b45fa590b8
