### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: pabeles/concurrency/ConcurrencyOps

### ISSUE THREAD

**Issue by sc3sc3** [lessthanoptimal/BoofCV#431]
Hi, 

I'm using boofcv via maven with
```
  <dependency>
    <groupId>org.boofcv</groupId>
    <artifactId>boofcv-all</artifactId>
    <version>1.1.6</version>
</dependency>
```

and get the following error:
Exception in thread "main" java.lang.NoClassDefFoundError: pabeles/concurrency/ConcurrencyOps
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at boofcv.io.image.ConvertRaster.bufferedToGray(ConvertRaster.java:115)
	at boofcv.io.image.ConvertBufferedImage.convertFrom(ConvertBufferedImage.java:424)
	at boofcv.io.image.ConvertBufferedImage.convertFromSingle(ConvertBufferedImage.java:342)

anything I'm doing wrong ?

Thanks

**Comment by lessthanoptimal** [comment]
That's odd. Are you mixing versions or something? Were you able to resolve this?

**Comment by sc3sc3** [comment]
yes, I got it working
but don't remember how.

**Comment by vanyle** [comment]
I just had the same issue.

It probably means that "ejml" was not in the class path. If you are using gradle, consider deleting your gradle cache (or maven cache) and redownloading your dependencies.

If you are managing your jar and classpath manually, know that you'll probably need to add the following Jars to your classpath:
`org.ejml:ejml-core`,  `org.ejml:ejml-fdense`, ` org.ejml:ejml-simple`, `org.ejml:ejml-ddense`, `org.ejml:ejml-cdense` and `org.ejml:ejml-fsparse`

You can see on mvnrepository that boofcv depends on ddogleg which depends on ejml which contains the missing class:
https://mvnrepository.com/artifact/org.ddogleg/ddogleg/0.24.0

You can use mvnrepository to know what are the exact versions you need.
