### ISSUE TITLE
ConvertBufferedImage.convertTo fails for alpha band images

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#47]
![output](https://cloud.githubusercontent.com/assets/2632538/14486545/c2bd62c2-015d-11e6-89de-8a6a3792e1b9.png)
BoofCV 0.23

I have a PNG which is decoded as TYPE_4BYTE_ABGR, as soon as I want to convert to Planar it fails:

java.lang.IllegalArgumentException: Unequal number of bands src = 4 dst = 3
    at boofcv.io.image.ConvertRaster.multToBuffered_U8(ConvertRaster.java:1599)
    at boofcv.io.image.ConvertBufferedImage.convertTo_U8(ConvertBufferedImage.java:736)
    at boofcv.io.image.ConvertBufferedImage.convertTo(ConvertBufferedImage.java:606)

**Comment by lessthanoptimal** [comment]
I think there needs to be an easy way to let the convertImage adjust the number of bands.  These errors have been a nuisance for a while.
