### ISSUE TITLE
Could not copy MANIFEST.MF to '/home/chris/Downloads/BoofCV/examples/build/tmp/jar/MANIFEST.MF'.

### ISSUE THREAD

**Issue by brizey02** [lessthanoptimal/BoofCV#88]
* What went wrong:
Could not copy MANIFEST.MF to '/home/chris/Downloads/BoofCV/examples/build/tmp/jar/MANIFEST.MF'.
> A Jar can only accept a valid file or directory: /home/chris/Downloads/BoofCV/examples/build/osgi-classes

**Comment by lessthanoptimal** [comment]
Can you type out exactly how you tried to build it? Did you follow the quick start instructions in the readme.md?

**Comment by brizey02** [comment]
Follow the read me instructions. Oracle JDK 9 on 14.05

**Comment by lessthanoptimal** [comment]
I think I know what's going on. This is a gradle bug. Which version are you building? Source of the code?
 github master? github snapshot? downloaded source code from sourceforge... etc.

**Comment by lessthanoptimal** [comment]
If the problem is what I think it is the hack work around is to comment out the following from boodfcv/build.gradle

```apply plugin: 'osgi'```

```
jar {
        manifest { // the manifest of the default jar is of type OsgiManifest
            instruction 'Bundle-Vendor', 'BoofCV'
//            instruction 'Bundle-Description', 'BoofCV'
            instruction 'Bundle-DocURL', 'http://boofcv.org'
        }
    }
```

**Comment by brizey02** [comment]
Skipping integration/android because ANDROID_HOME has not been set!  See integration/android/readme.txt
Skipping integration/boofcv-openkinect because boofcv-openkinect/libfreenect is missing! See integration/openkinect/readme.txt
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A Jar can only accept a valid file or directory: /home/chris/Downloads/BoofCV/examples/build/osgi-classes

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: A Jar can only accept a valid file or directory: /home/chris/Downloads/BoofCV/examples/build/osgi-classes
        at aQute.bnd.osgi.Jar.<init>(Jar.java:81)
        at aQute.bnd.osgi.Jar.<init>(Jar.java:99)
        at aQute.bnd.osgi.Analyzer.setJar(Analyzer.java:1369)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest.setAnalyzerProperties(DefaultOsgiManifest.java:125)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest.getEffectiveManifest(DefaultOsgiManifest.java:69)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest_Decorated.getEffectiveManifest(Unknown Source)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest.getEffectiveManifest(DefaultOsgiManifest.java:35)
        at org.gradle.api.java.archives.internal.DefaultManifest.writeTo(DefaultManifest.java:197)
        at org.gradle.api.java.archives.internal.DefaultManifest.writeTo(DefaultManifest.java:191)
        at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:76)
        at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:63)
        at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.copyTo(MapFileTree.java:184)
        at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.generateContent(MapFileTree.java:202)
        at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.updateFileOnlyWhenGeneratedContentChanges(MapFileTree.java:190)
        at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.getFile(MapFileTree.java:174)
        at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$FileVisitorImpl.visitFile(DefaultFileSystemSnapshotter.java:224)
        at org.gradle.api.internal.file.collections.MapFileTree$Visit.visit(MapFileTree.java:135)
        at org.gradle.api.internal.file.collections.MapFileTree.visit(MapFileTree.java:88)
        at org.gradle.api.internal.file.collections.MapFileTree.visitTreeOrBackingFile(MapFileTree.java:252)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visitTreeOrBackingFile(FileTreeAdapter.java:125)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visitTreeOrBackingFile(AbstractFileTree.java:196)
        at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshotTree(DefaultFileSystemSnapshotter.java:159)
        at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitTree(AbstractFileCollectionSnapshotter.java:90)
        at org.gradle.api.internal.file.AbstractFileTree.visitRootElements(AbstractFileTree.java:149)
        at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
        at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:51)
        at org.gradle.api.internal.changedetection.state.DefaultGenericFileCollectionSnapshotter.snapshot(DefaultGenericFileCollectionSnapshotter.java:36)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:89)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:58)
        at org.gradle.api.internal.changedetection.rules.InputFilesTaskStateChanges.<init>(InputFilesTaskStateChanges.java:31)
        at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:63)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:192)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.ensureSnapshotBeforeTask(DefaultTaskArtifactStateRepository.java:162)
        at org.gradle.api.internal.changedetection.changes.ShortCircuitTaskArtifactStateRepository$RerunTaskArtifactState.ensureSnapshotBeforeTask(ShortCircuitTaskArtifactStateRepository.java:107)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)


* Get more help at https://help.gradle.org

BUILD FAILED in 12s
46 actionable tasks: 12 executed, 34 up-to-date

**Comment by brizey02** [comment]
jar {
        manifest { // the manifest of the default jar is of type OsgiManifest
//            instruction 'Bundle-Vendor', 'BoofCV'
//            instruction 'Bundle-Description', 'BoofCV'
            instruction 'Bundle-DocURL', 'http://boofcv.org'
        }
    }

**Comment by lessthanoptimal** [comment]
Could you provide the location you obtained the source code you're trying to compile? There are some slight differences. Also let me know if commenting out the lines I mentioned above fixes the problem. I'm assuming those error messages was generated without commenting them out since OSGI is still mentioned.

**Comment by brizey02** [comment]
git clone https://github.com/lessthanoptimal/BoofCV.git

**Comment by lessthanoptimal** [comment]
I've removed OSGI from build.gradle. Fixed the problem. Some people might complain...

**Comment by stiv-yakovenko** [comment]
I still have this problem: https://stackoverflow.com/questions/47536817/error-building-boofcv-calibration-app-with-gradle?noredirect=1#comment82033250_47536817
