### ISSUE TITLE
java.lang.NoClassDefFoundError: org.ddogleg.struct.FastQueue in Android project

### ISSUE THREAD

**Issue by Wissperwind** [lessthanoptimal/BoofCV#93]
Hi,
Yesterday I added BoofCV to my Android project. I am able to code and Compile everything well. But at runtime there occours the following error:
 java.lang.NoClassDefFoundError: org.ddogleg.struct.FastQueue
                                                                             at boofcv.alg.feature.detect.line.HoughTransformLineFootOfNorm.<init>(HoughTransformLineFootOfNorm.java:56)
                                                                             at boofcv.abst.feature.detect.line.DetectLineHoughFoot.<init>(DetectLineHoughFoot.java:104)
                                                                             at boofcv.factory.feature.detect.line.FactoryDetectLineAlgs.houghFoot(FactoryDetectLineAlgs.java:115)
                                                                             at de.activities.MainActivity$1.onClick(MainActivity.java:61)
Even after hours of searching I can't get it work.

**Comment by Wissperwind** [comment]
I think this is coaused by a conflict with other libraries which I am using. In an empty project everything works fine.
